# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm ci
    # - run: npm test
    - name: Build
      run: npm run build --if-present
    - name: Artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
  publish:
      runs-on: ubuntu-latest
      steps:
          # The logic below handles the npm publication:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
                node-version: 18
                registry-url: "https://registry.npmjs.org"
          - run: npm whoami
            env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          - name: Download Artifact
            uses: actions/download-artifact@master
            with:
              name: build
              path: build
  
          - run: npm publish
            env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
